### ISSUE TITLE
Use admin_head instead of a controller plugin to add the datepicker script

### ISSUE THREAD

**Issue by zerocrates** [biblibre/omeka-plugin-Date#2]
The current use of the controller plugin seems like an unnecessary complication for just adding a script to the page `head`.

The [admin_head](http://omeka.readthedocs.org/en/latest/Reference/hooks/admin_head.html) hook should work just as well and not require any additional classes. You can access the Request from that hook by using the front controller:

```php
$request = Zend_Controller_Front::getInstance()->getRequest();
```

**Comment by jajm** [comment]
Works great: https://github.com/biblibre/omeka-plugin-Date/commit/ac1cff17b7c76843596957265d26692273df853b
Thanks!
